[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = ['typescript']

[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'thinca/vim-prettyprint'
on_cmd = ['PP', 'PrettyPrint']

[[plugins]]
repo = 'thinca/vim-fontzoom'
on_cmd = ['Fontzoom']
on_map = ['<Plug>(fontzoom-']
gui = 1

[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'tacahiroy/ctrlp-funky'
on_cmd = ['CtrlPFunky']

[[plugins]]
repo = 'suy/vim-ctrlp-commandline'
on_cmd = ['CtrlPCommandLine']

[[plugins]]
repo = 'rking/ag.vim'
on_cmd = ['Ag']

[[plugins]]
repo = 'preservim/nerdtree'
on_cmd = ['NERDTreeToggle']

